spring:
  application:
    name: bookstore

  datasource:
    username: ${db.user:bookstore_user}
    password: ${db.password:bookstore_password}
    url: jdbc:postgresql://${db.host:localhost}:${db.port:5432}/${db.name:bookstore_db}?currentSchema=public

  jooq:
    sql-dialect: postgres

  flyway:
    schemas: public
